worker_processes 1;

events { worker_connections 1024; }

http {

    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile        on;

    keepalive_timeout  65;

    server {
        listen 80;

        # разадача статики с эндпоинта /
        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }


        # раздача статики с эндпоинта /login
        location /login {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }

        # разадача статики с эндпоинта /profile/<int>
        location ~ ^/profile/\d+$  {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }

        # индексация папки images для выдачи картинок
        root /usr/share/nginx/html;
        location /images/ {
            autoindex on;
        }


        # Проксирование запросов /api к FastAPI
        location /api/ {
            proxy_pass http://api:8000/api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
